In [1]:
import pandas as pd

In [10]:
data = pd.read_excel('house-Mar2018-final.xls', header=1, index_cols=1, usecols='A:G'+',I:J', skiprows=[1,2,3],
                    skipfooter=1, names=['Suburb', '1stQ17', '2ndQ17', '3rdQ17', '4thQ17', '1stQ18', 'Sales No. 18',
                                        '% 1stQ17 to 1stQ18', '% 4thQ17 to 1stQ18'])

In [11]:
data

,Suburb,1stQ17,2ndQ17,3rdQ17,4thQ17,1stQ18,Sales No. 18,% 1stQ17 to 1stQ18,% 4thQ17 to 1stQ18
0,ABERFELDIE,1375000,1372500,1536000,1625000,1600000,9,16.4,-1.5
1,AINTREE,499000,513500,580000,590800,614000,8,23.0,3.9
2,AIREYS INLET,802500,735000,685000,785000,780000,11,-2.8,-0.6
3,AIRPORT WEST,771500,862000,860000,842000,870000,25,12.8,3.3
4,ALBANVALE,465000,525000,561000,546000,547000,19,17.6,0.2
5,ALBERT PARK,1929000,2130000,2420000,2085000,2120000,18,9.9,1.7
6,ALBION,685000,716500,642500,769000,702500,8,2.6,-8.6
7,ALEXANDRA,335000,217500,375000,275000,367000,13,9.6,33.5
8,ALFREDTON,410000,417500,414000,415000,420000,79,2.4,1.2
9,ALPHINGTON,1583500,1810000,1730000,1870000,1720000,5,8.6,-8.0
10,ALTONA,853000,977500,927800,1010000,970000,29,13.7,-4.0
11,ALTONA EAST,810000,885000,832500,950000,907500,12,12.0,-4.5
12,ALTONA MEADOWS,544000,582500,670000,732800,635000,17,16.7,-13.3
13,ALTONA NORTH,800000,826000,835000,847500,870000,23,8.8,2.7
14,ANGLESEA,725000,807500,720000,790000,870000,25,20.0,10.1
15,APOLLO BAY,500000,542000,550000,567500,522000,22,4.4,-8.0
16,ARARAT,225000,196500,203000,195000,190000,51,-15.6,-2.6
17,ARDEER,550000,645000,636000,615000,630000,21,14.5,2.4
18,ARMADALE,1947500,2105500,2137500,2202500,1445000,19,-25.8,-34.4
19,ARMSTRONG CREEK,470000,472000,460000,498300,523000,33,11.3,5.0
20,ASCOT (GREATER BENDIGO),386500,315000,352500,355300,390500,4,1.0,9.9
21,ASCOT VALE,1240000,1200000,1151000,1175000,1080000,29,-12.9,-8.1
22,ASHBURTON,1760000,1850000,1812500,1935000,1816000,14,3.2,-6.1
23,ASHWOOD,1325000,1417500,1415000,1450000,1380000,13,4.2,-4.8
24,ASPENDALE,1045600,1200000,1100000,1150000,1061500,16,1.5,-7.7
25,ASPENDALE GARDENS,831000,911000,863800,960000,1015000,15,22.1,5.7
26,ATTWOOD,665000,687500,775000,762500,675000,8,1.5,-11.5
27,AVENEL,390000,338000,295000,370000,340000,4,-12.8,-8.1
28,AVOCA,215000,220000,187500,229000,182500,6,-15.1,-20.3
29,AVONDALE HEIGHTS,850000,874500,855300,865000,824000,22,-3.1,-4.7
...,...,...,...,...,...,...,...,...,...
742,WHITTLESEA,467500,445000,469000,500000,570000,19,21.9,14.0
743,WILLIAMS LANDING,563600,636000,599500,653800,690000,26,22.4,5.5
744,WILLIAMSTOWN,1410000,1412000,1490000,1595000,1470000,37,4.3,-7.8
745,WILLIAMSTOWN NORTH,1400500,1122500,1055000,1160000,830000,3,-40.7,-28.4
746,WIMBLEDON HEIGHTS,310000,308000,440000,349500,337500,2,8.9,-3.4
747,WINCHELSEA,305000,387500,328000,381500,356000,12,16.7,-6.7
748,WINDSOR,1520000,1388000,1452000,1315000,1550000,15,2.0,17.9
749,WINTER VALLEY,373500,361000,375000,385000,381500,14,2.1,-0.9
750,WODONGA,335000,340000,352000,331300,350000,93,4.5,5.7
751,WOLLERT,491500,525000,550000,582500,596300,76,21.3,2.4
752,WONGA PARK,962500,957000,1211000,870000,1005000,3,4.4,15.5
753,WONTHAGGI,325000,269500,279500,305500,317500,38,-2.3,3.9
754,WOODEND,538500,505000,538000,622000,635000,11,17.9,2.1
755,WOOLAMAI WATERS,405800,425000,416500,455000,422000,28,4.0,-7.3
756,WOORI YALLOCK,429000,442000,505000,515000,500000,11,16.6,-2.9
757,WURRUK,220000,282500,235000,457500,325000,1,47.7,-29.0
758,WY YUNG,367500,367500,317500,400000,284500,4,-22.6,-28.9
759,WYE RIVER,755000,865800,820000,530000,930000,4,23.2,75.5
760,WYNDHAM VALE,390000,415000,450000,473000,475000,91,21.8,0.4
761,YACKANDANDAH,412500,437600,399000,532500,438000,5,6.2,-17.7
762,YALLAMBIE,773000,785600,750000,843000,775000,4,0.3,-8.1
763,YALLOURN NORTH,185000,167500,168000,165000,156800,7,-15.2,-5.0
764,YARRA GLEN,600000,590000,680000,665000,731000,7,21.8,9.9
765,YARRA JUNCTION,514500,480000,495000,586500,575000,14,11.8,-2.0
766,YARRAGON,345000,280000,279000,275500,400000,9,15.9,45.2
767,YARRAM,157500,315000,222500,230000,223500,17,41.9,-2.8
768,YARRAVILLE,994000,1087500,1000000,968000,1034800,43,4.1,6.9
769,YARRAWONGA,307500,315000,345500,329000,340000,57,10.6,3.3
770,YEA,370000,482500,355000,397500,380000,11,2.7,-4.4
771,YINNAR,221300,300000,270000,188000,227000,3,2.6,20.7